#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'miniMaxSum' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def miniMaxSum(arr):
    z = 0
    y = 0
    c = 0
    arr.sort()
    for i in arr:
        y = y + i
        c = c + 1
        if c == 4:
            break
    arr.sort(reverse=True)
    c = 0
    for b in arr:
        z = z + b
        c = c + 1
        if c == 4:
            break
    
    print(y, z)
    
if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
