#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'plusMinus' function below.
#
# The function accepts INTEGER_ARRAY arr as parameter.
#

def plusMinus(arr):
    # Write your code here
    x = 0
    y = 0
    w = 0
    for z in arr:
        if z < 0: # negative
            y = y+1 
        elif z > 0: # positive
            x = x+1 
        elif z == 0: # zero
            w = w+1
    if x > 0:
        print("{:6f}".format(x/n))
    else:
        print("0.000000")
    if y > 0:
        print("{:6f}".format(y/n))
    else:
        print("0.000000")
    if w > 0:
        print("{:6f}".format(w/n))
    else:
        print("0.000000")
    

if __name__ == '__main__':
    n = int(input().strip())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
